---
- name: test script to copy files
  hosts: all
  
  
  tasks:
  - copy:
      src: "{{ item }}"
      dest: "/opt/test/dist"
      owner: "root"
      mode: 0600
    with_fileglob:
      - "/var/log/messages"