---
- name: test script to copy files
  hosts: all
  become: yes
  
  tasks:
  - find: 
      paths: /opt/test/src 
      recurse: yes 
      patterns: 'a-*'
      register: file_to_copy
  - copy: 
      src: {{ item.paths }} 
      dest: /opt/test/dist
      with_items: "{{ file_to_copy.files }}"