---
- name: test script to copy files
  hosts: all
  become: yes
  
  tasks:
  - copy:
      src: "{{ item }}"
      dest: "/var/log/archieve_messsage"
      owner: "root"
      mode: 0600
    with_fileglob:
      - "/var/log/messages"