---
- name: test script to copy files
  hosts: all
  become_user: root
  become: true
    
  tasks:
  - copy:
      src: "{{ item }}"
      dest: "/opt/test/dist"
    
    with_fileglob:
      - "/var/log/messages*"