---
- name:  archieve /var/log/message files
  hosts: all
  become: true
  
  tasks:
  - name: copy files from one location to other
    copy:
      src: /opt/test/src/a.txt
      dist: /opt/test/src/a.txt