---
- name: test script to copy files
  hosts: all
  become: yes
  
  tasks:
  - copy:
      src: "{{ item }}"
      dest: "/var/log/archieve_messsage"
    with_fileglob:
      - "/var/log/messages-*"