---
- name: Archieve using cronjobs
  hosts: all
  become: true
  
  cron:
    name: "Archieve /var/log/messages"
    minute: "22"
    hour: "16"
    weekday: "0-6"
    job: "/opt/test/filemove.sh > /opt/test/filemove.sh.log 2>&1"
        
  tags:
   - cronjobs
