---
- name: creating a module to archieve /var/log messages
  hosts: all
  become: true
  
  tasks:
  - copy:
      src: /opt/test/src/a.txt
      dest: /var/log/archieve
      remote_src: yes
      