---
- name: Archieve using cronjobs
  hosts: all
  become: true
  
  cron:
    name: "Archieve /var/log/messages"
    job: "/opt/test/filemove.sh > /opt/test/filemove.sh.log 2>&1"
        
  tags:
   - cronjobs
