---
- name: creating a module to archieve /var/log messages
  hosts: all
  become: true
  
  tasks:
  - copy:
      src: /var/log/messages
      dest: /opt/test/dist
      remote_src: yes
      